### ISSUE TITLE
/ecs command not available addon doesn't appear to load

### ISSUE THREAD

**Issue by mcjustin71** [BreakBB/ExtendedCharacterStats#90]
Recently did a reinstall and reworking my addons, after installation and loading I am receiving the the error below and module doesnt appear to load.
please see the error below:
Date: 2021-01-10 15:18:33
ID: 8
Error occured in: Global
Count: 1
Message: ...\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua line 41:
   attempt to index field 'texts' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [C]: ?
   ...\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua:41:
      ...\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua:34
   (tail call): ?
   ...Ons\ExtendedCharacterStats\Modules\SlashCommands.lua:22: ?()
   ..\FrameXML\ChatFrame.lua:4693: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4356: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4392: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
AddOns:
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  BagBrother
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  Details, vv1.13.5.215 (core 142)
  DetailsStreamer
  DetailsTinyThreat
  ExtendedCharacterStats, v2.7.0
  GatherMate2, v1.45.6-classic
  GearQuipper, v41
  GuildRosterManager, v1.927
  HealBot, v1.13.6.2
  HealBotData, v1.13.6.1
  HealBoten, v1.13.6.1
  HealBotExtraSkins, v1.13.6.1
  HealBotOptions, v1.13.6.1
  HealBotTips, v1.13.6.1
  NauticusClassic, v1.3.1
  NovaWorldBuffs, v1.86
  PowerRaid, v3.2.4
  RaidInvites, v1.0
  Swatter, v5.0.0
  ThreatClassic2, v2.27
  WeakAuras, v3.1.8
  ZPerl, v6.1.4
  ZPerlArcaneBar
  ZPerlPartyPet
  ZPerlParty
  ZPerlPlayerBuffs
  ZPerlPlayerPet
  ZPerlPlayer
  ZPerlRaidAdmin
  ZPerlRaidFrames
  ZPerlRaidHelper
  ZPerlRaidMonitor
  ZPerlRaidPets
  ZPerlTargetTarget
  ZPerlTarget
  TradeSkillMaster, vv4.10.28
  CommunityDKP, v3.2.3
  DBMCore, v1.13.67-3-gaa01f9b
  DBMDefaultSkin
  DBMStatusBarTimers

**Comment by BreakBB** [comment]
Hey @mcjustin71 does the error appear once you login or when you run the `/ecs` command?

Also which language are you using for WoW Classic?

**Comment by mcjustin71** [comment]
Good Morning, I get an 2 Errors Onload below and the error above when i run the /ecs command.   I am also using US-English for language.
Thank you

Date: 2021-01-11 09:09:13
ID: 51
Error occured in: Global
Count: 1
Message: ..\AddOns\ExtendedCharacterStats\ECS.lua line 48:
   attempt to index field 'general' (a nil value)
Debug:
   [C]: ?
   ExtendedCharacterStats\ECS.lua:48:
      ExtendedCharacterStats\ECS.lua:41
   ExtendedCharacterStats\ECS.lua:31:
      ExtendedCharacterStats\ECS.lua:28
AddOns:
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  BagBrother
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  Details, vv1.13.5.215 (core 142)
  DetailsStreamer
  DetailsTinyThreat
  ExtendedCharacterStats, v2.7.0
  Swatter, v5.0.0
  CommunityDKP, v3.2.3
  DBMCore, v1.13.67-4-gcd5a44b
  DBMDefaultSkin
  DBMStatusBarTimers

----------------------------------------------------------------------------------------------------------------------------------------
Date: 2021-01-11 09:09:17
ID: 52
Error occured in: Global
Count: 1
Message: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua line 44:
   attempt to index field 'general' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [C]: ?
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:44: CreateWindow()
   ExtendedCharacterStats\ECS.lua:102:
      ExtendedCharacterStats\ECS.lua:100
   ExtendedCharacterStats\ECS.lua:35:
      ExtendedCharacterStats\ECS.lua:28
AddOns:
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  BagBrother
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  Details, vv1.13.5.215 (core 142)
  DetailsStreamer
  DetailsTinyThreat
  ExtendedCharacterStats, v2.7.0
  GatherMate2, v1.45.6-classic
  GearQuipper, v41
  GuildRosterManager, v1.927
  HealBot, v1.13.6.2
  HealBotData, v1.13.6.1
  HealBoten, v1.13.6.1
  HealBotOptions, v1.13.6.1
  HealBotTips, v1.13.6.1
  NauticusClassic, v1.3.1
  NovaWorldBuffs, v1.86
  PowerRaid, v3.2.4
  RaidInvites, v1.0
  Swatter, v5.0.0
  ThreatClassic2, v2.27
  WeakAuras, v3.1.8
  ZPerl, v6.1.4
  ZPerlArcaneBar
  ZPerlPartyPet
  ZPerlParty
  ZPerlPlayerBuffs
  ZPerlPlayerPet
  ZPerlPlayer
  ZPerlRaidAdmin
  ZPerlRaidFrames
  ZPerlRaidHelper
  ZPerlRaidMonitor
  ZPerlRaidPets
  ZPerlTargetTarget
  ZPerlTarget
  TradeSkillMaster, vv4.10.28
  CommunityDKP, v3.2.3
  DBMCore, v1.13.67-4-gcd5a44b
  DBMDefaultSkin
  DBMStatusBarTimers

-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by BreakBB** [comment]
Hey @mcjustin71 thanks for coming back to this really quick 👍 

Could you try this version? I am not totally sure yet what is causing the `/ecs` issue, but the latter ones you posted should be fixed with this.

[ExtendedCharacterStats-v2.7.0_0-5245e98.zip](https://github.com/BreakBB/ExtendedCharacterStats/files/5797534/ExtendedCharacterStats-v2.7.0_0-5245e98.zip)

**Comment by mcjustin71** [comment]
Still getting the errors on load and on the /ecs command.  However I can now see the plate on the char sheet with that version, however it is blank
![ECS_error](https://user-images.githubusercontent.com/32003761/104231522-f2cba700-5403-11eb-92ae-a93801c2b97b.jpg)
Date: 2021-01-11 11:56:33
ID: 51
Error occured in: Global
Count: 1
Message: ..\AddOns\ExtendedCharacterStats\ECS.lua line 61:
   attempt to concatenate local 'currentProfileVersion' (a nil value)
Debug:
   [C]: ?
   ExtendedCharacterStats\ECS.lua:61:
      ExtendedCharacterStats\ECS.lua:41
   ExtendedCharacterStats\ECS.lua:31:
      ExtendedCharacterStats\ECS.lua:28
AddOns:
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  BagBrother
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  Details, vv1.13.5.215 (core 142)
  DetailsStreamer
  DetailsTinyThreat
  ExtendedCharacterStats, v2.7.0
  Swatter, v5.0.0
  CommunityDKP, v3.2.3
  DBMCore, v1.13.67-4-gcd5a44b
  DBMDefaultSkin
  DBMStatusBarTimers

--------------------------------------------------------------------------------------------------------------------------------------
Date: 2021-01-11 11:56:38
ID: 52
Error occured in: Global
Count: 1
Message: ...\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua line 41:
   attempt to index field 'texts' (a nil value)
Debug:
   ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:758:
      ...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717
   [C]: ?
   ...\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua:41:
      ...\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua:34
   (tail call): ?
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:49: CreateWindow()
   ExtendedCharacterStats\ECS.lua:103:
      ExtendedCharacterStats\ECS.lua:101
   ExtendedCharacterStats\ECS.lua:35:
      ExtendedCharacterStats\ECS.lua:28
AddOns:
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  BagBrother
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  Details, vv1.13.5.215 (core 142)
  DetailsStreamer
  DetailsTinyThreat
  ExtendedCharacterStats, v2.7.0
  GatherMate2, v1.45.6-classic
  GearQuipper, v41
  GuildRosterManager, v1.927
  HealBot, v1.13.6.2
  HealBotData, v1.13.6.1
  HealBoten, v1.13.6.1
  HealBotOptions, v1.13.6.1
  HealBotTips, v1.13.6.1
  NauticusClassic, v1.3.1
  NovaWorldBuffs, v1.86
  PowerRaid, v3.2.4
  RaidInvites, v1.0
  Swatter, v5.0.0
  ThreatClassic2, v2.27
  WeakAuras, v3.1.8
  ZPerl, v6.1.4
  ZPerlArcaneBar
  ZPerlPartyPet
  ZPerlParty
  ZPerlPlayerBuffs
  ZPerlPlayerPet
  ZPerlPlayer
  ZPerlRaidAdmin
  ZPerlRaidFrames
  ZPerlRaidHelper
  ZPerlRaidMonitor
  ZPerlRaidPets
  ZPerlTargetTarget
  ZPerlTarget
  TradeSkillMaster, vv4.10.28
  CommunityDKP, v3.2.3
  DBMCore, v1.13.67-4-gcd5a44b
  DBMDefaultSkin
  DBMStatusBarTimers

**Comment by BreakBB** [comment]
Okay, thanks again for helping out here 😁 

You should try the version below which should fix the first issue. For the second one you could try to run the following command and then do a `/reload`:

`/run ExtendedCharacterStats = nil`

[Uploading ExtendedCharacterStats-v2.7.0_0-5245e98.zip…]()

**Comment by mcjustin71** [comment]
link above just reloads the page :)  thank you!

**Comment by BreakBB** [comment]
Argh damn it, sorry. Fixed the link @mcjustin71

**Comment by mcjustin71** [comment]
Same issues, looks like same errors.

**Comment by BreakBB** [comment]
@mcjustin71 Did you try the run command I wrote above?

**Comment by mcjustin71** [comment]
yes i ran the command
/run ExtendedCharacterStats = nil
and did /reload
several times

**Comment by mcjustin71** [comment]
I reverted back to 2.6.3 and I am no longer experiencing any issues.  Those 3 error dumps from swatter were consistent even with the updated builds you provided.   Thank you!

**Comment by BreakBB** [comment]
Hey @mcjustin71 can you send me your saved variables for ECS? You can find them inside you WTF folder. They are called `ExtendedCharacterStats.lua` and `ExtendedCharacterStats.lua.bak`. Simply add them to a ZIP file and drag and drop them inside the comment section here.

There might be something else wrong which I simply can not think of.

I am very sorry that you have trouble with the latest update and would really like to solve the problem.

**Comment by BreakBB** [comment]
Hey @mcjustin71 I just published a fixed version. I hope your issues are fixed with it as well. If not go ahead and notify me!

**Comment by BreakBB** [comment]
Closing this issue due to inactivity
